spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
      url: jdbc:h2:mem:maindb
  liquibase:
    enabled: true
  sql:
    init:
      mode: never
      data-locations: data.sql
      schema-locations: schema.sql